# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [2]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [3]:
import pandas as pd
import datetime

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data)

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [4]:
url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data'

In [5]:
data = pd.read_csv(url,sep='\s+', parse_dates=[[0,1,2]])

In [6]:
data.head()

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,2061-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,2061-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,2061-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,2061-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,2061-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [9]:
def date(x):
    year = x.year-100 if x.year>1989 else x.year
    return datetime.date(year, x.month, x.day)

In [10]:
data['Yr_Mo_Dy'] = data['Yr_Mo_Dy'].apply(date)

In [11]:
data.head()

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [13]:
data['Yr_Mo_Dy'] = pd.to_datetime(data['Yr_Mo_Dy'])

In [14]:
data.set_index('Yr_Mo_Dy', inplace=True)

In [15]:
data.index

DatetimeIndex(['1961-01-01', '1961-01-02', '1961-01-03', '1961-01-04',
               '1961-01-05', '1961-01-06', '1961-01-07', '1961-01-08',
               '1961-01-09', '1961-01-10',
               ...
               '1978-12-22', '1978-12-23', '1978-12-24', '1978-12-25',
               '1978-12-26', '1978-12-27', '1978-12-28', '1978-12-29',
               '1978-12-30', '1978-12-31'],
              dtype='datetime64[ns]', name='Yr_Mo_Dy', length=6574, freq=None)

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [16]:
data.isnull().sum()

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

### Step 7. Compute how many non-missing values there are in total.

In [17]:
data.notnull().sum()

RPT    6568
VAL    6571
ROS    6572
KIL    6569
SHA    6572
BIR    6574
DUB    6571
CLA    6572
MUL    6571
CLO    6573
BEL    6574
MAL    6570
dtype: int64

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [18]:
data.sum().sum()

806540.2299999988

In [19]:
data.notna().sum().sum()

78857

In [20]:
data.sum().sum() / data.notna().sum().sum()

10.227883764282167

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.

In [21]:
loc_stats = data.describe(percentiles=[.5])
loc_stats

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
count,6568.000000,6571.000000,6572.000000,6569.000000,6572.000000,6574.000000,6571.000000,6572.000000,6571.000000,6573.000000,6574.000000,6570.000000
mean,12.362987,10.644314,11.660526,6.306468,10.455834,7.092254,9.797343,8.495053,8.493590,8.707332,13.121007,15.599079
std,5.618413,5.267356,5.008450,3.605811,4.936125,3.968683,4.977555,4.499449,4.166872,4.503954,5.835037,6.699794
min,0.670000,0.210000,1.500000,0.000000,0.130000,0.000000,0.000000,0.000000,0.000000,0.040000,0.130000,0.670000
50%,11.710000,10.170000,10.920000,5.750000,9.960000,6.830000,9.210000,8.080000,8.170000,8.290000,12.500000,15.000000
max,35.800000,33.370000,33.840000,28.460000,37.540000,26.160000,30.370000,31.080000,25.880000,28.210000,42.380000,42.540000

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [22]:
data.transpose().describe(percentiles=[]).transpose().drop(['count','50%'],axis=1).head()

                 mean       std   min    max
Yr_Mo_Dy
1961-01-01  13.018182  2.808875  9.29  18.50
1961-01-02  11.336364  3.188994  6.50  17.54
1961-01-03  11.641818  3.681912  6.17  18.50
1961-01-04   6.619167  3.198126  1.79  11.75
1961-01-05  10.630000  2.445356  6.17  13.33

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [23]:
data.index.month

Int64Index([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
            ...
            12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
           dtype='int64', name='Yr_Mo_Dy', length=6574)

In [24]:
data[data.index.month == 1].mean()

RPT    14.847325
VAL    12.914560
ROS    13.299624
KIL     7.199498
SHA    11.667734
BIR     8.054839
DUB    11.819355
CLA     9.512047
MUL     9.543208
CLO    10.053566
BEL    14.550520
MAL    18.028763
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.

In [25]:
data.groupby(data.index.year).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
1962,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
1963,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
1964,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
1965,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
1966,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
1967,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
1968,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
1969,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
1970,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
1971,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
1972,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
1973,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
1974,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
1975,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
1976,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
1977,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
1978,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

In [26]:
#data.groupby(data.index.to_period('A')).mean()

### Step 13. Downsample the record to a monthly frequency for each location.

In [27]:
data.groupby(data.index.to_period('M')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961-01,14.841333,11.988333,13.431613,7.736774,11.072759,8.588065,11.184839,9.245333,9.085806,10.107419,13.880968,14.703226
1961-02,16.269286,14.975357,14.441481,9.230741,13.852143,10.937500,11.890714,11.846071,11.821429,12.714286,18.583214,15.411786
1961-03,10.890000,11.296452,10.752903,7.284000,10.509355,8.866774,9.644194,9.829677,10.294138,11.251935,16.410968,15.720000
1961-04,10.722667,9.427667,9.998000,5.830667,8.435000,6.495000,6.925333,7.094667,7.342333,7.237000,11.147333,10.278333
1961-05,9.860968,8.850000,10.818065,5.905333,9.490323,6.574839,7.604000,8.177097,8.039355,8.499355,11.900323,12.011613
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-08,9.645161,8.259355,9.032258,4.502903,7.368065,5.935161,5.650323,5.417742,7.241290,5.536774,10.466774,12.054194
1978-09,10.913667,10.895000,10.635000,5.725000,10.372000,9.278333,10.790333,9.583000,10.069333,8.939000,15.680333,19.391333
1978-10,9.897742,8.670968,9.295806,4.721290,8.525161,6.774194,8.115484,7.337742,8.297742,8.243871,13.776774,17.150000
1978-11,16.151667,14.802667,13.508000,7.317333,11.475000,8.743000,11.492333,9.657333,10.701333,10.676000,17.404667,20.723000
1978-12,16.175484,13.748065,15.635161,7.094839,11.398710,9.241613,12.077419,10.194839,10.616774,11.028710,13.859677,21.371613

### Step 14. Downsample the record to a weekly frequency for each location.

In [28]:
data.groupby(data.index.to_period('W')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1960-12-26/1961-01-01,15.040000,14.960000,13.170000,9.290000,NaN,9.870000,13.670000,10.250000,10.830000,12.580000,18.500000,15.040000
1961-01-02/1961-01-08,13.541429,11.486667,10.487143,6.417143,9.474286,6.435714,11.061429,6.616667,8.434286,8.497143,12.481429,13.238571
1961-01-09/1961-01-15,12.468571,8.967143,11.958571,4.630000,7.351429,5.072857,7.535714,6.820000,5.712857,7.571429,11.125714,11.024286
1961-01-16/1961-01-22,13.204286,9.862857,12.982857,6.328571,8.966667,7.417143,9.257143,7.875714,7.145714,8.124286,9.821429,11.434286
1961-01-23/1961-01-29,19.880000,16.141429,18.225714,12.720000,17.432857,14.828571,15.528571,15.160000,14.480000,15.640000,20.930000,22.530000
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-11-27/1978-12-03,14.934286,11.232857,13.941429,5.565714,10.215714,8.618571,9.642857,7.685714,9.011429,9.547143,11.835714,18.728571
1978-12-04/1978-12-10,20.740000,19.190000,17.034286,9.777143,15.287143,12.774286,14.437143,12.488571,13.870000,14.082857,18.517143,23.061429
1978-12-11/1978-12-17,16.758571,14.692857,14.987143,6.917143,11.397143,7.272857,10.208571,7.967143,9.168571,8.565714,11.102857,15.562857
1978-12-18/1978-12-24,11.155714,8.008571,13.172857,4.004286,7.825714,6.290000,7.798571,8.667143,7.151429,8.072857,11.845714,18.977143
1978-12-25/1978-12-31,14.951429,11.801429,16.035714,6.507143,9.660000,8.620000,13.708571,10.477143,10.868571,11.471429,12.947143,26.844286

### Step 15. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [35]:
weekly = data.resample('W').agg(['mean','max','min','std'])
weekly

                  RPT                                VAL                \
                 mean    max    min       std       mean    max    min
Yr_Mo_Dy
1961-01-01  15.040000  15.04  15.04       NaN  14.960000  14.96  14.96
1961-01-08  13.541429  18.50  10.58  2.631321  11.486667  16.88   6.63
1961-01-15  12.468571  19.75   9.04  3.555392   8.967143  12.08   3.54
1961-01-22  13.204286  19.83   4.92  5.337402   9.862857  14.37   3.42
1961-01-29  19.880000  25.04  13.62  4.619061  16.141429  23.91   9.96
...               ...    ...    ...       ...        ...    ...    ...
1978-12-03  14.934286  21.29   9.08  4.931754  11.232857  21.34   4.54
1978-12-10  20.740000  29.33   9.92  7.215012  19.190000  24.79  12.54
1978-12-17  16.758571  23.13   9.87  4.499431  14.692857  24.04   3.21
1978-12-24  11.155714  16.62   6.21  3.522759   8.008571  13.29   3.63
1978-12-31  14.951429  20.33   7.21  4.350400  11.801429  17.41   5.46

                            ROS         ...    CLO                  BEL  \
                 std       mean    max  ...    min       std       mean
Yr_Mo_Dy                                ...
1961-01-01       NaN  13.170000  13.17  ...  12.58       NaN  18.500000
1961-01-08  3.949525  10.487143  12.33  ...   5.88  1.704941  12.481429
1961-01-15  3.148945  11.958571  19.50  ...   2.67  4.084293  11.125714
1961-01-22  3.837785  12.982857  20.79  ...   2.71  4.783952   9.821429
1961-01-29  5.170224  18.225714  25.84  ...  11.04  3.713368  20.930000
...              ...        ...    ...  ...    ...       ...        ...
1978-12-03  5.978968  13.941429  24.04  ...   3.29  6.284973  11.835714
1978-12-10  4.953060  17.034286  25.37  ...   6.75  5.516405  18.517143
1978-12-17  7.578665  14.987143  18.05  ...   2.67  5.487801  11.102857
1978-12-24  3.882900  13.172857  22.21  ...   4.71  3.023131  11.845714
1978-12-31  4.705392  16.035714  27.29  ...   3.08  5.533397  12.947143

                                          MAL
              max    min       std       mean    max    min        std
Yr_Mo_Dy
1961-01-01  18.50  18.50       NaN  15.040000  15.04  15.04        NaN
1961-01-08  17.54   5.46  4.349139  13.238571  16.46  10.88   1.773062
1961-01-15  20.71   5.25  5.552215  11.024286  16.92   5.17   4.692355
1961-01-22  15.92   6.50  3.626584  11.434286  17.96   6.79   4.237239
1961-01-29  27.71  14.04  5.210726  22.530000  27.63  17.50   3.874721
...           ...    ...       ...        ...    ...    ...        ...
1978-12-03  21.42   4.92  5.950112  18.728571  25.75  11.50   6.393188
1978-12-10  26.08   9.54  5.600389  23.061429  34.59  15.34   8.093976
1978-12-17  21.50   5.00  6.631925  15.562857  22.83   6.92   6.005594
1978-12-24  19.79   3.21  5.750301  18.977143  31.71  10.29   7.194108
1978-12-31  21.79   1.21  7.523148  26.844286  41.46  11.96  11.621233

[940 rows x 48 columns]

In [36]:
weekly.loc[weekly.index[1:53]]

                  RPT                                VAL                \
                 mean    max    min       std       mean    max    min
Yr_Mo_Dy
1961-01-08  13.541429  18.50  10.58  2.631321  11.486667  16.88   6.63
1961-01-15  12.468571  19.75   9.04  3.555392   8.967143  12.08   3.54
1961-01-22  13.204286  19.83   4.92  5.337402   9.862857  14.37   3.42
1961-01-29  19.880000  25.04  13.62  4.619061  16.141429  23.91   9.96
1961-02-05  16.827143  24.21  10.58  5.251408  15.460000  24.21   9.46
1961-02-12  19.684286  24.54  16.00  3.587677  16.417143  21.42  11.54
1961-02-19  15.130000  22.50   6.04  5.064609  15.091429  20.17  11.63
1961-02-26  15.221429  25.80   7.79  7.020716  13.625714  21.50   7.08
1961-03-05  12.101429  13.33  10.96  0.997721  12.951429  17.00   8.83
1961-03-12   9.376667  14.79   4.88  3.732263  11.578571  16.96   8.08
1961-03-19  11.911429  16.88   4.92  3.860036  13.501429  15.54   9.46
1961-03-26   9.567143  15.00   6.29  3.613298   8.387143  11.63   2.58
1961-04-02  10.757143  18.25   5.88  5.046922   8.852857  16.29   3.50
1961-04-09  11.964286  18.12   4.50  4.604392  10.654286  14.62   7.04
1961-04-16   8.965714  15.50   4.71  3.937727   8.000000  12.25   4.83
1961-04-23  12.621429  21.09   4.00  5.676655  10.438571  15.41   3.71
1961-04-30  10.117143  16.29   4.08  4.349662   9.798571  14.46   6.50
1961-05-07  15.367143  23.00   9.87  5.025507  13.970000  19.79  10.29
1961-05-14   7.772857  12.79   3.54  3.371022   8.712857  15.12   3.96
1961-05-21   8.225714  15.04   4.88  3.631730   5.631667  10.17   3.58
1961-05-28   8.155714  11.79   4.96  2.739433   7.388571  12.50   3.67
1961-06-04  10.321429  15.92   7.00  3.099701   7.407143   9.79   4.75
1961-06-11  10.917143  14.42   8.29  2.248597   8.992857  11.54   6.83
1961-06-18  10.571429  14.33   6.13  3.009482   9.565714  14.54   4.12
1961-06-25   7.345714   9.00   4.00  1.982035   6.108571   9.50   3.25
1961-07-02  10.236667  13.13   7.21  2.557856   9.482857  14.37   6.34
1961-07-09  11.715714  17.50   7.29  3.664855   7.220000  10.75   3.75
1961-07-16  16.680000  22.50   8.63  5.168710  13.518571  19.29   7.87
1961-07-23   4.202857   5.88   3.04  1.047978   4.255714   6.79   2.92
1961-07-30  10.561429  16.08   6.13  4.157641   8.445714  13.79   4.63
1961-08-06  10.870000  16.08   7.67  2.950887   8.792857  15.79   5.09
1961-08-13  10.058333  14.21   2.88  4.422268   7.941429  10.00   4.42
1961-08-20  15.607143  18.91  13.13  2.283635  10.565714  13.62   7.25
1961-08-27  12.391429  18.16   7.67  3.395857  11.430000  14.58   6.87
1961-09-03   8.678571  14.46   3.63  4.398615   8.821429  22.00   1.13
1961-09-10  10.541429  17.62   5.00  5.207278   8.798571  13.59   3.04
1961-09-17  17.160000  28.75   5.33  7.679190  14.440000  22.08   7.12
1961-09-24   8.500000  10.25   6.92  1.267399   7.154286  13.62   2.92
1961-10-01  16.044286  23.21  10.34  4.559572  11.361667  13.62   6.96
1961-10-08  11.250000  16.08   3.13  5.596710   8.757143  16.96   3.63
1961-10-15  10.881667  17.12   3.71  4.780675   9.734286  13.25   6.13
1961-10-22  19.260000  28.62  10.46  7.888314  13.364286  19.46   3.75
1961-10-29  16.077143  26.42   4.33  7.957637  11.867143  21.25   2.75
1961-11-05  11.571429  15.79   5.88  3.369201   9.590000  13.46   3.96
1961-11-12  10.428571  16.08   5.46  3.939811   7.690000  10.75   5.50
1961-11-19  10.798571  15.00   7.50  2.784358   7.951429  13.00   4.21
1961-11-26   9.154286  14.29   5.75  3.214368   7.337143  11.79   3.29
1961-12-03  12.608571  23.75   7.92  5.704669  10.442857  18.71   4.67
1961-12-10  17.362857  23.71  10.83  4.890152  14.362857  21.37   9.21
1961-12-17  14.985714  21.34   9.29  4.095106  13.472857  17.62   8.63
1961-12-24  15.757143  24.41  11.46  4.959717  11.971429  16.13   9.79
1961-12-31  13.634286  20.54   5.04  5.787783   9.504286  16.04   3.08

                            ROS         ...    CLO                  BEL  \
                 std       mean    max  ...    min       std       mean
Yr_Mo_Dy                                ...
1961-01-08  3.949525  10.487143  12.33  ...   5.88  1.704941  12.481429
1961-01-15  3.148945  11.958571  19.50  ...   2.67  4.084293  11.125714
1961-01-22  3.837785  12.982857  20.79  ...   2.71  4.783952   9.821429
1961-01-29  5.170224  18.225714  25.84  ...  11.04  3.713368  20.930000
1961-02-05  5.187395  12.618571  19.70  ...   5.50  2.839501  14.012857
1961-02-12  3.608373  17.304286  21.34  ...  12.25  1.746749  21.832857
1961-02-19  3.575012  13.797143  19.41  ...   9.21  2.531361  21.167143
1961-02-26  5.147348  14.334286  22.42  ...   7.00  4.920064  16.304286
1961-03-05  2.851955  11.063333  13.67  ...   9.79  1.593685  17.842857
1961-03-12  3.230167  10.845714  16.38  ...   5.09  3.655113  16.701429
1961-03-19  2.352867  11.607143  13.96  ...   7.29  3.099472  19.350000
1961-03-26  3.657265   9.695714  15.63  ...   8.33  2.538224  14.037143
1961-04-02  4.687315   9.501429  14.96  ...   6.46  3.191115  13.471429
1961-04-09  2.845399  13.607143  18.29  ...   3.67  2.336182  11.712857
1961-04-16  2.607118   8.787143  15.79  ...   4.00  2.161137   9.482857
1961-04-23  4.631736  10.255714  17.00  ...   3.83  3.347972  13.620000
1961-04-30  2.871425   8.281429  14.96  ...   2.71  2.840568   9.720000
1961-05-07  3.750835  13.834286  21.21  ...   8.63  3.620819  17.548571
1961-05-14  3.782947   8.172857  12.33  ...   1.83  5.460237  10.421429
1961-05-21  2.468906  12.042857  15.96  ...   4.17  2.216889   9.624286
1961-05-28  3.378537   8.512857  20.96  ...   5.17  2.575661  10.518571
1961-06-04  1.868125  10.065714  15.96  ...   5.91  2.096989  12.298571
1961-06-11  1.524836   8.095714  11.58  ...   5.21  2.158323  10.148571
1961-06-18  3.509444  10.875714  15.50  ...   3.08  3.792400  15.351429
1961-06-25  2.212460   8.084286  10.37  ...   7.83  2.286218  14.370000
1961-07-02  2.902411   8.648571  10.79  ...   7.96  1.564144  14.535714
1961-07-09  2.686658   9.320000  14.92  ...   6.21  3.657179  12.220000
1961-07-16  3.849630  11.171429  14.29  ...   4.25  3.271899  13.520000
1961-07-23  1.400010   6.738571  12.67  ...   3.92  1.439785   7.524286
1961-07-30  3.203206   9.352857  15.67  ...   4.92  4.350268  12.841429
1961-08-06  3.985226   9.858571  15.59  ...   5.41  2.903018  11.595714
1961-08-13  2.053326   8.728571  11.63  ...   5.25  2.073777  10.934286
1961-08-20  2.523416  11.065714  14.04  ...   9.13  2.730237  14.922857
1961-08-27  3.174702  12.768571  17.83  ...   7.46  3.855302  16.251429
1961-09-03  7.474025   6.745714  12.75  ...   5.96  3.993736  13.664286
1961-09-10  4.003996   8.185714  14.88  ...   1.75  3.649278  10.700000
1961-09-17  5.360585  15.617143  26.50  ...   9.67  5.128338  19.878571
1961-09-24  3.445262   7.993333  12.17  ...   2.83  2.354092  11.018571
1961-10-01  2.812482  13.062857  17.58  ...   5.29  3.908397  16.208571
1961-10-08  5.060803  10.167143  17.83  ...   2.42  4.296870   8.810000
1961-10-15  2.707483   9.104286  20.96  ...   5.37  3.569308  14.451429
1961-10-22  5.998199  15.828571  22.63  ...  11.08  5.890511  17.477143
1961-10-29  6.879973  14.608571  23.09  ...   5.83  6.277629  15.592857
1961-11-05  3.900278  10.827143  14.33  ...   7.67  2.784450  16.322857
1961-11-12  2.141191  10.272857  20.41  ...   2.62  2.843518   9.208571
1961-11-19  3.208548  16.988571  32.71  ...   1.25  4.402588   5.875714
1961-11-26  3.277904   8.662857  14.46  ...   6.92  2.747452  11.772857
1961-12-03  5.107089  11.481429  19.92  ...   3.63  3.680477  11.464286
1961-12-10  4.115506  15.460000  20.54  ...   5.75  4.156207  15.975714
1961-12-17  3.587886  13.720000  19.00  ...   4.67  4.633398  15.112857
1961-12-24  2.220866  12.840000  22.13  ...   2.46  4.637096   9.958571
1961-12-31  4.566479  15.804286  29.33  ...   1.96  3.526625   9.697143

                                          MAL
              max    min       std       mean    max    min       std
Yr_Mo_Dy
1961-01-08  17.54   5.46  4.349139  13.238571  16.46  10.88  1.773062
1961-01-15  20.71   5.25  5.552215  11.024286  16.92   5.17  4.692355
1961-01-22  15.92   6.50  3.626584  11.434286  17.96   6.79  4.237239
1961-01-29  27.71  14.04  5.210726  22.530000  27.63  17.50  3.874721
1961-02-05  19.33   9.17  4.210858  11.935714  19.25   7.17  4.336104
1961-02-12  26.38  15.21  4.063753  19.155714  21.84  17.04  1.828705
1961-02-19  29.63  14.09  5.910938  16.584286  22.58  10.96  4.685377
1961-02-26  23.21   9.59  5.091162  14.322857  23.87   6.67  6.182283
1961-03-05  23.45  11.58  4.332331  13.951667  17.54   8.83  3.021387
1961-03-12  22.71  10.21  4.358759  14.420000  22.54   5.54  5.769890
1961-03-19  22.79  11.29  3.779727  16.227143  22.95  11.34  4.331958
1961-03-26  21.34   8.25  4.318069  18.134286  22.50  13.13  3.701846
1961-04-02  18.63   7.21  4.179854  13.900000  19.58   7.17  3.924555
1961-04-09  17.16   7.62  3.147781  11.371429  15.34   7.21  2.598271
1961-04-16  16.17   5.75  3.641464   8.690000  12.87   5.66  2.747842
1961-04-23  19.21   6.75  4.735096  12.470000  20.46   4.96  5.908542
1961-04-30  13.04   5.13  2.948237   8.637143  17.50   2.67  5.108365
1961-05-07  28.08   4.79  8.003490  14.571429  26.58   3.83  7.728504
1961-05-14  18.66   6.54  3.968272  10.382857  26.30   3.33  7.858246
1961-05-21  12.00   6.63  1.975853  10.612857  14.96   5.91  3.310819
1961-05-28  14.33   6.13  3.024524  11.697143  17.04   8.00  3.811818
1961-06-04  17.00   8.71  2.611139  13.597143  17.96  10.63  2.593586
1961-06-11  16.17   5.37  3.993062  12.250000  19.83   5.96  4.925055
1961-06-18  25.25   7.29  6.477887  15.025714  24.71   6.13  6.242673
1961-06-25  19.08  11.00  2.498386  17.410000  21.50  13.75  3.063011
1961-07-02  21.87   6.96  6.303747  12.133333  16.79   8.50  3.652313
1961-07-09  20.41   7.08  4.537988  15.987143  21.29  12.08  3.665705
1961-07-16  20.25   5.04  4.971060  12.524286  21.96   5.96  4.974273
1961-07-23  10.13   4.21  2.050218   8.415714  10.92   5.41  2.133994
1961-07-30  22.17   7.87  5.580903  13.761429  25.37   6.13  6.664574
1961-08-06  18.54   6.17  4.901377  13.760000  20.25   9.08  4.448251
1961-08-13  14.29   5.88  2.931302  10.125714  15.16   5.88  3.356585
1961-08-20  21.92   9.59  4.086725  16.626667  24.30  13.04  3.934238
1961-08-27  23.38   5.75  6.711322  16.485714  22.29   8.29  4.947608
1961-09-03  24.71   4.79  7.678051  11.022857  22.54   5.41  6.308087
1961-09-10  15.83   5.41  4.220584  11.034286  20.25   3.37  6.049619
1961-09-17  23.91  13.92  4.464252  18.984286  33.09  14.67  6.332885
1961-09-24  20.96   4.54  5.235868   9.814286  14.62   5.25  3.113507
1961-10-01  21.37   7.79  5.091268  13.338571  17.16   4.04  4.696504
1961-10-08  17.83   4.79  4.800403  11.410000  19.62   4.83  5.462002
1961-10-15  20.46   8.54  4.113200  15.260000  21.04  10.75  4.098130
1961-10-22  24.71  10.88  5.645871  23.641429  33.45  13.46  7.468377
1961-10-29  27.29   8.50  7.056150  18.404286  30.88   9.83  8.340881
1961-11-05  20.17  10.29  4.038493  19.195714  23.58  13.37  3.870800
1961-11-12  12.58   6.13  2.532196  10.858571  15.54   5.71  3.690752
1961-11-19   9.59   0.71  3.643285   5.737143  13.25   2.00  3.787654
1961-11-26  20.46   6.50  5.407223  12.732857  22.58   4.25  6.475867
1961-12-03  19.04   5.50  5.552648  14.725714  21.29   5.88  5.233192
1961-12-10  21.79  10.71  4.667933  16.241429  29.33   7.58  7.345893
1961-12-17  22.83   5.50  6.531043  14.644286  21.12   6.50  5.665006
1961-12-24  17.67   5.29  5.065308   8.164286  16.62   2.62  5.048035
1961-12-31  13.21   3.75  3.262217  12.840000  15.21   6.63  3.012729

[52 rows x 48 columns]